name: GeminiCraft
version: 2.0.1
main: dev.geminicraft.GeminiCraft
api-version: 1.18
commands:
  gemini:
    description: GeminiCraft main command
    usage: /gemini [help|ask|enable|disable|toggle]
permissions:
  geminicraft.admin:
    default: op